######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 23 18:14:20 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += log_in_window.h messenger.h messenger_window.h
SOURCES += log_in_window.cpp main.cpp messenger.cpp messenger_window.cpp
